MapleDKPStaticData = {
    defaultNewMemberDkp = 180,
    activeRaiderWindowSeconds = 30 * 24 * 60 * 60,
    bossSchemaVersion = 4,

    defaultBosses = {
        ["15550"] = { name = "Attumen the Huntsman", amount = 10, zone = "Karazhan", encounterOrder = 1 },
        ["15687"] = { name = "Moroes", amount = 10, zone = "Karazhan", encounterOrder = 2 },
        ["16457"] = { name = "Maiden of Virtue", amount = 10, zone = "Karazhan", encounterOrder = 3 },
        ["17521"] = { name = "Opera Event: Big Bad Wolf", amount = 10, zone = "Karazhan", encounterOrder = 4 },
        ["18168"] = { name = "Opera Event: The Crone", amount = 10, zone = "Karazhan", encounterOrder = 5 },
        ["17534"] = { name = "Opera Event: Romulo and Julianne", amount = 10, zone = "Karazhan", encounterOrder = 6 },
        ["15691"] = { name = "The Curator", amount = 10, zone = "Karazhan", encounterOrder = 7 },
        ["15688"] = { name = "Terestian Illhoof", amount = 10, zone = "Karazhan", encounterOrder = 8 },
        ["16524"] = { name = "Shade of Aran", amount = 10, zone = "Karazhan", encounterOrder = 9 },
        ["15689"] = { name = "Netherspite", amount = 10, zone = "Karazhan", encounterOrder = 10 },
        ["16816"] = { name = "Chess Event", amount = 10, zone = "Karazhan", encounterOrder = 11 },
        ["15690"] = { name = "Prince Malchezaar", amount = 20, zone = "Karazhan", encounterOrder = 12 },
        ["17225"] = { name = "Nightbane", amount = 10, zone = "Karazhan", encounterOrder = 13 },
        ["16179"] = { name = "Hyakiss the Lurker", amount = 10, zone = "Karazhan", encounterOrder = 14 },
        ["16180"] = { name = "Shadikith the Glider", amount = 10, zone = "Karazhan", encounterOrder = 15 },
        ["16181"] = { name = "Rokad the Ravager", amount = 10, zone = "Karazhan", encounterOrder = 16 },
        ["18831"] = { name = "High King Maulgar", amount = 10, zone = "Gruul's Lair", encounterOrder = 1 },
        ["19044"] = { name = "Gruul the Dragonkiller", amount = 20, zone = "Gruul's Lair", encounterOrder = 2 },
        ["17257"] = { name = "Magtheridon", amount = 20, zone = "Magtheridon's Lair", encounterOrder = 1 },
        ["21216"] = { name = "Hydross the Unstable", amount = 10, zone = "Serpentshrine Cavern", encounterOrder = 1 },
        ["21215"] = { name = "Leotheras the Blind", amount = 10, zone = "Serpentshrine Cavern", encounterOrder = 2 },
        ["21213"] = { name = "Morogrim Tidewalker", amount = 10, zone = "Serpentshrine Cavern", encounterOrder = 3 },
        ["21212"] = { name = "Lady Vashj", amount = 20, zone = "Serpentshrine Cavern", encounterOrder = 4 },
        ["19514"] = { name = "Al'ar", amount = 10, zone = "Tempest Keep", encounterOrder = 1 },
        ["19516"] = { name = "Void Reaver", amount = 10, zone = "Tempest Keep", encounterOrder = 2 },
        ["18805"] = { name = "High Astromancer Solarian", amount = 10, zone = "Tempest Keep", encounterOrder = 3 },
        ["19622"] = { name = "Kael'thas Sunstrider", amount = 20, zone = "Tempest Keep", encounterOrder = 4 },
        ["23576"] = { name = "Nalorakk", amount = 10, zone = "Zul'Aman", encounterOrder = 1 },
        ["23574"] = { name = "Akil'zon", amount = 10, zone = "Zul'Aman", encounterOrder = 2 },
        ["23578"] = { name = "Jan'alai the Dragonhawk Lord", amount = 10, zone = "Zul'Aman", encounterOrder = 3 },
        ["23577"] = { name = "Halazzi the Lynx Lord", amount = 10, zone = "Zul'Aman", encounterOrder = 4 },
        ["24239"] = { name = "Hex Lord Malacrass", amount = 10, zone = "Zul'Aman", encounterOrder = 5 },
        ["23863"] = { name = "Zul'jin", amount = 20, zone = "Zul'Aman", encounterOrder = 6 },
        ["17767"] = { name = "Rage Winterchill", amount = 10, zone = "Mount Hyjal", encounterOrder = 1 },
        ["17808"] = { name = "Anetheron", amount = 10, zone = "Mount Hyjal", encounterOrder = 2 },
        ["17888"] = { name = "Kaz'rogal", amount = 10, zone = "Mount Hyjal", encounterOrder = 3 },
        ["17842"] = { name = "Azgalor", amount = 10, zone = "Mount Hyjal", encounterOrder = 4 },
        ["17968"] = { name = "Archimonde", amount = 20, zone = "Mount Hyjal", encounterOrder = 5 },
        ["22887"] = { name = "High Warlord Naj'entus", amount = 10, zone = "Black Temple", encounterOrder = 1 },
        ["22898"] = { name = "Supremus", amount = 10, zone = "Black Temple", encounterOrder = 2 },
        ["22841"] = { name = "Shade of Akama", amount = 10, zone = "Black Temple", encounterOrder = 3 },
        ["22871"] = { name = "Teron Gorefiend", amount = 10, zone = "Black Temple", encounterOrder = 4 },
        ["22948"] = { name = "Gurtogg Bloodboil", amount = 10, zone = "Black Temple", encounterOrder = 5 },
        ["23418"] = { name = "Reliquary of Souls", amount = 10, zone = "Black Temple", encounterOrder = 6 },
        ["22947"] = { name = "Mother Shahraz", amount = 10, zone = "Black Temple", encounterOrder = 7 },
        ["22949"] = { name = "Illidari Council", amount = 10, zone = "Black Temple", encounterOrder = 8 },
        ["22917"] = { name = "Illidan Stormrage", amount = 20, zone = "Black Temple", encounterOrder = 9 },
        ["24850"] = { name = "Kalecgos", amount = 10, zone = "Sunwell Plateau", encounterOrder = 1 },
        ["24882"] = { name = "Brutallus", amount = 10, zone = "Sunwell Plateau", encounterOrder = 2 },
        ["25038"] = { name = "Felmyst", amount = 10, zone = "Sunwell Plateau", encounterOrder = 3 },
        ["25165"] = { name = "Eredar Twins", amount = 10, zone = "Sunwell Plateau", encounterOrder = 4 },
        ["25741"] = { name = "M'uru", amount = 10, zone = "Sunwell Plateau", encounterOrder = 5 },
        ["25315"] = { name = "Kil'jaeden", amount = 20, zone = "Sunwell Plateau", encounterOrder = 6 },
    },

    zoneSortOrder = {
        ["Karazhan"] = 1,
        ["Gruul's Lair"] = 2,
        ["Magtheridon's Lair"] = 3,
        ["Serpentshrine Cavern"] = 4,
        ["Tempest Keep"] = 5,
        ["Zul'Aman"] = 6,
        ["Mount Hyjal"] = 7,
        ["Black Temple"] = 8,
        ["Sunwell Plateau"] = 9,
        ["Custom"] = 100,
    },

    classNameToToken = {
        ["PALADIN"] = "PALADIN",
        ["WARRIOR"] = "WARRIOR",
        ["HUNTER"] = "HUNTER",
        ["MAGE"] = "MAGE",
        ["SHAMAN"] = "SHAMAN",
        ["PRIEST"] = "PRIEST",
        ["WARLOCK"] = "WARLOCK",
        ["ROGUE"] = "ROGUE",
        ["DRUID"] = "DRUID",
    },

    classColorHex = {
        ["PALADIN"] = "FFF58CBA",
        ["WARRIOR"] = "FF8B5A2B",
        ["HUNTER"] = "FF2E8B57",
        ["MAGE"] = "FF87CEFA",
        ["SHAMAN"] = "FF1E90FF",
        ["PRIEST"] = "FFFFFFFF",
        ["WARLOCK"] = "FF9370DB",
        ["ROGUE"] = "FFFFFF66",
        ["DRUID"] = "FFFF8C00",
    },
}
